apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    system: a01
    group: base
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email-flask-svc
        image: adxautomationbase.azurecr.io/email:0.2.0
        ports:
        - containerPort: 80
        env:
        - name: A01_STORE_NAME
          value: store-internal-svc
        - name: A01_INTERNAL_COMKEY
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: comkey
        - name: A01_REPORT_SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: email
              key: server
        - name: A01_REPORT_SENDER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: email
              key: username
        - name: A01_REPORT_SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email
              key: password
      imagePullSecrets:
      - name: adxautomationbase-registry
---
apiVersion: v1
kind: Service
metadata:
  name: email-internal-svc
  labels:
    system: a01
    group: base
spec:
  ports:
  - port: 80
  selector:
    app: email
