apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: report-deployment
  labels:
    system: a01
    group: base
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
      - name: report-svc
        command: ["powerbi"]
        image: adxautomationbase.azurecr.io/powerbi:0.1.0
        ports:
        - containerPort: 80
        env:
        - name: A01_POWERBI_CLIENT_ID
          valueFrom:  
            secretKeyRef:
              name: email
              key: powerbi.client.id
        - name: A01_POWERBI_USERNAME
          valueFrom:
            secretKeyRef:
              name: email
              key: username
        - name: A01_POWERBI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email
              key: password
      imagePullSecrets:
      - name: adxautomationbase-registry
---
apiVersion: v1
kind: Service
metadata:
  name: report-internal-svc
  labels:
    system: a01
    group: base
spec:
  ports:
  - port: 80
  selector:
    app: report
