apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    system: a01
    group: base
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store-flask-svc
        image: adxautomationbase.azurecr.io/store:0.9.2
        ports:
        - containerPort: 80
        env:
        - name: A01_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: dburi
        - name: A01_INTERNAL_COMKEY
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: comkey 
      imagePullSecrets:
      - name: adxautomationbase-registry
---
  apiVersion: v1
  kind: Service
  metadata:
    name: store-internal-svc
    labels:
      system: a01
      group: base
  spec:
    ports:
    - port: 80
    selector:
      app: store
