"""empty message

Revision ID: 2bcdd6b22385
Revises: 9d5665354d34
Create Date: 2018-03-07 15:02:18.893844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcdd6b22385'
down_revision = '9d5665354d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'owner')
    # ### end Alembic commands ###
