#!/usr/bin/env bash

version=$TRAVIS_TAG

set -e

registry=adxautomationbase
image=$registry.azurecr.io/store:$version

pushd services/store

docker login $registry.azurecr.io -u $ACR_SP_USERNAME -p $ACR_SP_PASSWORD
docker pull $image >/dev/null 2>&1 && (echo The image $image already exists. >&2; exit 1)

docker build -t $image .
docker push $image

popd